### ISSUE TITLE
Cannot open include file: 'opensll/err.h' No such file or directory

### ISSUE THREAD

**Issue by SecuritySlayer** [heysurfer/EnetProxy#9]
![image](https://user-images.githubusercontent.com/49792134/174581946-5ad4b607-3d0b-4781-a8f5-6cc95f30a5f3.png)
I installed opensll like u said and still doesnt work

**Comment by RE3RY** [comment]
Also if you get any "LNK2001 unresolved external symbol __imp_" then add **#pragma comment( lib, "Winmm.lib" )** in proxy.cpp like this 
![image](https://user-images.githubusercontent.com/80929479/174598958-e86bb760-df31-4247-bbf2-31acdffb77c9.png)

**Comment by SecuritySlayer** [comment]
> Did you build proxy as x86 or x64?
> 
> for me x64 works but x86 gives same error that you get. So try to build as x64 ![image](https://user-images.githubusercontent.com/80929479/174598451-822d05a6-2ee8-4447-af4a-6ad55e320880.png)

I have installed 
![image](https://user-images.githubusercontent.com/49792134/174603669-109d7a7d-90ab-413d-ba72-729b8f8b8f1d.png)

And i have tried compilng with debug,release,x64,x86 every compile setting and i still get this
![image](https://user-images.githubusercontent.com/49792134/174603797-229272aa-6fae-4d18-a5ea-6b0513f4fb19.png)
I have even restarted my pc
Please contact me on discord Tajzia#0548 much faster response

**Comment by heysurfer** [comment]
hi,try `vcpkg install openssl`

https://github.com/openssl/openssl

**Comment by SecuritySlayer** [comment]
> 
![image](https://user-images.githubusercontent.com/49792134/174610235-0bf5c6b2-bc7c-49ea-b304-9a86e58198fe.png)
Hello, i installed it but for some reason i still get this issue

**Comment by SecuritySlayer** [comment]
> hi,try `vcpkg install openssl`
> 
> https://github.com/openssl/openssl
![image](https://user-images.githubusercontent.com/49792134/174610649-a75874a9-9921-4fe8-a4df-78df8bf6a0c1.png)
Hello, i installed it but for some reason i still get this issue

**Comment by Altanb21** [comment]
I get same error too

**Comment by SecuritySlayer** [comment]
> fixed after added this and restart computer #pragma comment( lib, "Winmm.lib" )

I added it and restarted my pc and i still get the same error 
![image](https://user-images.githubusercontent.com/49792134/174617908-1c48b4da-d4f7-472a-aa96-2198a195988e.png)

Add my discord Tajzia#0548

**Comment by Altanb21** [comment]
> > fixed after added this and restart computer #pragma comment( lib, "Winmm.lib" )
> 
> I added it and restarted my pc and i still get the same error ![image](https://user-images.githubusercontent.com/49792134/174617908-1c48b4da-d4f7-472a-aa96-2198a195988e.png)
> 
> Add my discord Tajzia#0548

download latest version

**Comment by Altanb21** [comment]
download latest version

**Comment by StrafeGod** [comment]
@SecuritySlayer did u solved the problem ? if u did can you add me on discord Strafe#3154
